#! /usr/bin/env bash

ask() {
  # http://djm.me/ask
  local prompt default REPLY

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read REPLY </dev/tty

    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

BASE_BRANCH=$1
BRANCH=$2

git checkout $BRANCH

COMMITS=$(git log --oneline --reverse $BASE_BRANCH..$BRANCH | grep -o "^[a-fA-F0-9]\+")

for COMMIT in $COMMITS; do
    git checkout $COMMIT
    git show
    FILE=$(git show --name-only --format="" | head -n1)
    if ask "Edit $FILE" Y; then
        vim $FILE
    fi
done

git checkout $BRANCH
